#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg
sudo chown  $USER:$USER /etc/default/haproxy

echo "ENABLED=1" > /etc/default/haproxy

echo "
frontend front_http
	bind *:80
	mode http
	default_backend backendServers

backend backendServers
	balance roundrobin
   	server 263707-web-01 34.232.78.135:80 check
   	server 263707-web-02 100.25.48.182:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
