#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get -y update
apt-get install -y haproxy=2.9.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
frontend front_http
	bind *:80
	default_backend backendServers

backend backendServers
	balance roundrobin
   	server 263707-web-01 34.232.78.135:80 check
   	server 263707-web-02 100.25.48.182:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
