#!/usr/bin/env bash
#pings a network

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

network="$1"

# Ping the network
ping -c 5 "$network"
