#!/usr/bin/env bash
#pings a network

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <network>"
    echo "Example: $0 192.168.1.0/24"
    exit 1
fi

network="$1"

# Ping the network
ping -c 5 "$network"
