#!/usr/bin/env bash
#Configures ubuntu server

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root or with sudo"
  exit 1
fi

# Add entry to hosts file
echo "127.0.0.2   localhost" >> /etc/hosts
echo "8.8.8.8   facebook.com" >> /etc/hosts
cp /etc/hosts ~/hosts.new
sed ... ~/hosts.new
cp -f ~/hosts.new /etc/hosts
